import { StyleSheet } from "react-native";
import { colors, spacing, borderRadius, fontSize, fontWeight, shadow } from "../constants/theme";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  header: {
    backgroundColor: colors.headerBg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(244,181,26,0.15)",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
  },
  headerTitle: {
    color: colors.white,
    fontSize: fontSize.title,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.3)",
  },
  headerBadgeText: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  mapOverlayTop: {
    position: "absolute",
    top: spacing.xxl,
    left: spacing.md,
    right: spacing.md,
    zIndex: 10,
    gap: spacing.xs,
  },
  compactStatsRow: {
    flexDirection: "column",
    gap: 4,
  },
  mapOverlayRight: {
    position: "absolute",
    top: spacing.xxl,
    right: spacing.md,
    zIndex: 10,
  },
  compactStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 3,
    paddingHorizontal: spacing.sm - 2,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,26,77,0.9)",
  },
  compactStatValue: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  compactStatLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 9,
    fontWeight: fontWeight.semibold,
  },
  filterBtnTextActive: {
    color: colors.accent,
    fontWeight: fontWeight.bold,
  },
  mapToggleRow: {
    flexDirection: "row",
    gap: spacing.xs,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  mapToggleBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: spacing.xs + 1,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.18)",
    backgroundColor: "#16253F",
    shadowColor: "#000",
    shadowOpacity: 0.35,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  mapToggleBtnOnReports: {
    backgroundColor: "#F4B51A",
    borderColor: "#F4B51A",
  },
  mapToggleBtnOnLocation: {
    backgroundColor: "#3B82F6",
    borderColor: "#3B82F6",
  },
  mapToggleText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: "#93A5C4",
  },
  mapToggleTextOnReports: {
    color: "#0F141A",
    fontWeight: fontWeight.bold,
  },
  mapToggleTextOnLocation: {
    color: colors.white,
    fontWeight: fontWeight.bold,
  },
  mapContainer: {
    flex: 1,
    overflow: "hidden",
  },
  contentWrap: {
    flex: 1,
  },
  triageSection: {
    backgroundColor: colors.primaryDark,
    paddingTop: spacing.sm + 2,
    paddingBottom: spacing.sm + 2,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(244,181,26,0.15)",
    zIndex: 5,
  },
  triageHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
  },
  triageHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  triageHeaderIcon: {
    width: 36,
    height: 36,
    borderRadius: 11,
    backgroundColor: "rgba(96,165,250,0.12)",
    borderWidth: 1,
    borderColor: "rgba(96,165,250,0.25)",
    justifyContent: "center",
    alignItems: "center",
  },
  triageTitle: {
    color: colors.white,
    fontSize: 16,
    fontWeight: "800",
    letterSpacing: 0.3,
  },
  triageSubtitle: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 10,
    fontWeight: "500",
    marginTop: 2,
  },
  triageChips: {
    paddingHorizontal: spacing.lg,
    gap: 8,
  },
  triageStatChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: borderRadius.round,
  },
  triageStatChipActive: {
    backgroundColor: "rgba(255,255,255,0.1)",
    borderColor: "rgba(255,255,255,0.25)",
  },
  triageStatLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 10,
    fontWeight: "700",
  },
  triageStatValue: {
    minWidth: 20,
    height: 18,
    paddingHorizontal: 6,
    borderRadius: 9,
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  triageStatValueText: {
    fontSize: 10,
    fontWeight: "800",
    color: "rgba(255,255,255,0.85)",
  },
  triageList: {
    paddingHorizontal: spacing.lg,
    paddingTop: 10,
    paddingBottom: 4,
    gap: 8,
  },
  triageCard: {
    width: 200,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
    overflow: "hidden",
  },
  triageCardBody: {
    padding: 10,
  },
  triageCardTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  triageCardType: {
    flex: 1,
    color: colors.white,
    fontSize: 12,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  triageCardMeta: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 8,
  },
  triageIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  triageRowScore: {
    fontSize: 10,
    fontWeight: "800",
    flexShrink: 0,
  },
  triagePriorityBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    flexShrink: 0,
  },
  triagePriorityText: {
    fontSize: 8.5,
    fontWeight: "800",
    letterSpacing: 0.6,
  },
  triageStatus: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    flexShrink: 0,
  },
  triageStatusText: {
    fontSize: 8.5,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  triageValidBadge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    flexShrink: 0,
  },
  triageValidText: {
    fontSize: 8.5,
    fontWeight: "800",
  },
  triageTime: {
    color: "rgba(255,255,255,0.4)",
    fontSize: 9,
    fontWeight: "600",
    flexShrink: 0,
  },
  triageEmpty: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 26,
    gap: 8,
  },
  triageEmptyText: {
    color: "rgba(255,255,255,0.35)",
    fontSize: 12,
    fontWeight: "600",
  },
  mapOverlayBottom: {
    position: "absolute",
    bottom: 12,
    left: 12,
    right: 12,
    zIndex: 10,
  },
  mapStatsRow: {
    flexDirection: "row",
    gap: 6,
  },
  mapStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: 5,
    paddingHorizontal: 9,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(0,10,32,0.9)",
  },
  mapStatValue: {
    fontSize: 11,
    fontWeight: "bold",
    color: colors.white,
  },
  mapStatLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 9,
    fontWeight: "semibold",
  },

  residentPanel: {
    flex: 1,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  residentPanelTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  residentItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    gap: spacing.md,
  },
  residentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  residentName: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  residentAddress: {
    fontSize: fontSize.sm,
    color: colors.textTertiary,
    marginTop: 1,
  },
  residentStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
  },
  residentStatusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "flex-end",
    padding: spacing.lg,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    width: "100%",
    maxHeight: "80%",
    paddingBottom: spacing.xxl,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "center",
    marginTop: spacing.sm + 2,
    marginBottom: spacing.xs,
  },
  modalCloseBtn: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalScrollContent: {
    paddingHorizontal: spacing.xxl,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  modalAvatar: {
    position: "relative",
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.06)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.accent,
  },
  modalAvatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  modalAvatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOnlineDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#22C55E",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  modalHeaderText: {
    flex: 1,
  },
  modalName: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  modalBadge: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.4)",
    marginTop: 2,
  },
  modalEmptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxxl,
    gap: spacing.md,
  },
  modalEmptyText: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.35)",
    textAlign: "center",
  },
  modalReportCard: {
    marginTop: spacing.lg,
  },
  modalReportCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  modalCrimeIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalReportCrime: {
    flex: 1,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.white,
    textTransform: "capitalize",
  },
  modalReportDate: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.35)",
    marginTop: 2,
  },
  modalReportDesc: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.6)",
    lineHeight: 20,
  },
  modalStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 2,
    borderRadius: borderRadius.round,
    alignSelf: "flex-start",
  },
  modalStatusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalDescWrap: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  modalLocRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  modalLocText: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.5)",
    flex: 1,
  },
  modalSectionLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: "rgba(255,255,255,0.35)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  modalEvidenceRow: {
    marginBottom: spacing.sm,
  },
  modalEvidenceImage: {
    width: 200,
    height: 150,
    borderRadius: borderRadius.lg,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  modalActionsDouble: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  modalAcceptBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#16A34A",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalAcceptBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalDeclineBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DC2626",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalDeclineBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalNavBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3B82F6",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalNavBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalStreetBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1e3a5f",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.3)",
  },
  modalStreetBtnText: {
    color: "#93C5FD",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingVertical: spacing.md + 2,
    borderRadius: borderRadius.lg,
    marginTop: spacing.lg,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.25)",
  },
  modalProfileBtnText: {
    color: colors.accent,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.base,
  },
});
