import { StyleSheet } from "react-native";

export const navigateStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#000",
  },
  map: {
    flex: 1,
  },
  headerOverlay: {
    position: "absolute",
    top: 48,
    left: 12,
    right: 12,
    zIndex: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.65)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
  },
  headerInfo: {
    flex: 1,
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  headerSub: {
    fontSize: 11,
    color: "rgba(255,255,255,0.45)",
    marginTop: 1,
  },
  badge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.2)",
  },
  badgeText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#F4B51A",
  },
  bottomPanel: {
    position: "absolute",
    bottom: 24,
    left: 12,
    right: 12,
    zIndex: 10,
    backgroundColor: "rgba(20,26,34,0.94)",
    borderRadius: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  waypointRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    gap: 8,
  },
  waypointCol: {
    flex: 1,
    alignItems: "center",
  },
  waypointDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginBottom: 4,
  },
  waypointLine: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  waypointLabel: {
    fontSize: 10,
    color: "rgba(255,255,255,0.35)",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: 2,
  },
  waypointValue: {
    fontSize: 13,
    color: "rgba(255,255,255,0.85)",
    fontWeight: "600",
    textAlign: "center",
    maxWidth: 100,
  },
  statsRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: 12,
    paddingVertical: 8,
    paddingHorizontal: 6,
  },
  statCard: {
    flex: 1,
    alignItems: "center",
    gap: 3,
  },
  statDivider: {
    width: 1,
    height: 28,
    backgroundColor: "rgba(255,255,255,0.06)",
  },
  statValue: {
    fontSize: 13,
    fontWeight: "700",
    color: "#FFFFFF",
  },
  statLabel: {
    fontSize: 9,
    color: "rgba(255,255,255,0.35)",
    fontWeight: "500",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  divider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: 8,
  },
  actionRow: {
    flexDirection: "row",
    gap: 8,
  },
  actionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 10,
    gap: 6,
  },
  actionBtnStreet: {
    backgroundColor: "#DBEAFE",
  },
  actionBtnReport: {
    backgroundColor: "rgba(244,181,26,0.12)",
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.2)",
  },
  actionBtnTextBlue: {
    color: "#1D4ED8",
    fontSize: 12,
    fontWeight: "700",
  },
  actionBtnTextReport: {
    color: "#F4B51A",
    fontSize: 12,
    fontWeight: "700",
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: "#0f141a",
  },
  loadingMapPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingCard: {
    position: "absolute",
    bottom: 40,
    left: 12,
    right: 12,
    backgroundColor: "rgba(20,26,34,0.94)",
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  loadingText: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 13,
    fontWeight: "500",
  },
  errorContainer: {
    flex: 1,
    backgroundColor: "#0f141a",
  },
  errorMapPlaceholder: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorCard: {
    position: "absolute",
    bottom: 40,
    left: 12,
    right: 12,
    backgroundColor: "rgba(20,26,34,0.94)",
    borderRadius: 18,
    padding: 24,
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  errorText: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 14,
    textAlign: "center",
    lineHeight: 20,
  },
  retryBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.25)",
  },
  retryBtnText: {
    color: "#F4B51A",
    fontWeight: "700",
    fontSize: 13,
  },
});
