import { StyleSheet } from "react-native";
import { colors, spacing, borderRadius, fontSize, fontWeight, shadow } from "../../constants/theme";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.primary,
  },
  header: {
    backgroundColor: colors.headerBg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(244,181,26,0.15)",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
  },
  headerTitle: {
    color: colors.white,
    fontSize: fontSize.title,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.3)",
  },
  headerBadgeText: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  mapOverlayTop: {
    position: "absolute",
    top: spacing.xxl,
    left: spacing.md,
    right: spacing.md,
    zIndex: 10,
    gap: spacing.xs,
  },
  compactStatsRow: {
    flexDirection: "column",
    gap: 4,
  },
  mapOverlayRight: {
    position: "absolute",
    top: spacing.xxl,
    right: spacing.md,
    zIndex: 10,
  },
  compactStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 3,
    paddingHorizontal: spacing.sm - 2,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,26,77,0.9)",
  },
  compactStatValue: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  compactStatLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 9,
    fontWeight: fontWeight.semibold,
  },
  filterRow: {
    flexDirection: "row",
    gap: spacing.xs,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  styleSwitcher: {
    flexDirection: "row",
    gap: 3,
  },
  styleBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(0,26,77,0.9)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  styleBtnActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  stylePickerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    justifyContent: "flex-end",
  },
  stylePickerPanel: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderBottomWidth: 0,
  },
  stylePickerHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "center",
    marginBottom: 16,
  },
  stylePickerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.white,
    marginBottom: 12,
  },
  stylePickerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 4,
  },
  stylePickerItemActive: {
    backgroundColor: "rgba(244,181,26,0.1)",
  },
  stylePickerItemText: {
    flex: 1,
    fontSize: 15,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },
  stylePickerItemTextActive: {
    color: colors.accent,
    fontWeight: "700",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: spacing.xs + 1,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(0,26,77,0.9)",
  },
  filterBtnActive: {
    backgroundColor: "rgba(244,181,26,0.15)",
    borderColor: colors.accent,
  },
  filterBtnText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: "rgba(255,255,255,0.55)",
  },
  filterBtnTextActive: {
    color: colors.accent,
    fontWeight: fontWeight.bold,
  },
  mapContainer: {
    flex: 1,
    overflow: "hidden",
  },

  residentPanel: {
    flex: 1,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  residentPanelTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  residentItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    gap: spacing.md,
  },
  residentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  residentName: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  residentAddress: {
    fontSize: fontSize.sm,
    color: colors.textTertiary,
    marginTop: 1,
  },
  residentStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
  },
  residentStatusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "flex-end",
    padding: spacing.lg,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    width: "100%",
    maxHeight: "80%",
    paddingBottom: spacing.xxl,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "center",
    marginTop: spacing.sm + 2,
    marginBottom: spacing.xs,
  },
  modalCloseBtn: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalScrollContent: {
    paddingHorizontal: spacing.xxl,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.06)",
  },
  modalAvatar: {
    position: "relative",
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: "rgba(255,255,255,0.06)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.accent,
  },
  modalAvatarImage: {
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  modalAvatarPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 26,
    justifyContent: "center",
    alignItems: "center",
  },
  modalOnlineDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: "#22C55E",
    borderWidth: 2,
    borderColor: colors.surface,
  },
  modalHeaderText: {
    flex: 1,
  },
  modalName: {
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  modalBadge: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.4)",
    marginTop: 2,
  },
  modalEmptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: spacing.xxxl,
    gap: spacing.md,
  },
  modalEmptyText: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.35)",
    textAlign: "center",
  },
  modalReportCard: {
    marginTop: spacing.lg,
  },
  modalReportCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
  },
  modalCrimeIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 12,
    backgroundColor: "rgba(255,255,255,0.06)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalReportCrime: {
    flex: 1,
    fontSize: fontSize.xl,
    fontWeight: fontWeight.bold,
    color: colors.white,
    textTransform: "capitalize",
  },
  modalReportDate: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.35)",
    marginTop: 2,
  },
  modalReportDesc: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.6)",
    lineHeight: 20,
  },
  modalStatusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 2,
    borderRadius: borderRadius.round,
    alignSelf: "flex-start",
  },
  modalStatusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  modalDescWrap: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  modalLocRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.06)",
  },
  modalLocText: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.5)",
    flex: 1,
  },
  modalSectionLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: "rgba(255,255,255,0.35)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginTop: spacing.xl,
    marginBottom: spacing.sm,
  },
  modalEvidenceRow: {
    marginBottom: spacing.sm,
  },
  modalEvidenceImage: {
    width: 200,
    height: 150,
    borderRadius: borderRadius.lg,
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  modalActionsDouble: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.xl,
  },
  modalAcceptBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#16A34A",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalAcceptBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalDeclineBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DC2626",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalDeclineBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalNavBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#3B82F6",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    ...shadow.button,
  },
  modalNavBtnText: {
    color: "#fff",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalStreetBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1e3a5f",
    paddingVertical: spacing.md + 4,
    borderRadius: borderRadius.lg,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(59,130,246,0.3)",
  },
  modalStreetBtnText: {
    color: "#93C5FD",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingVertical: spacing.md + 2,
    borderRadius: borderRadius.lg,
    marginTop: spacing.lg,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.25)",
  },
  modalProfileBtnText: {
    color: colors.accent,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.base,
  },
});
