import { StyleSheet } from "react-native";
import { colors, spacing, borderRadius, fontSize, fontWeight, shadow } from "../../constants/theme";

export const dashboardStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f141a",
  },
  header: {
    backgroundColor: "rgba(15,20,26,0.96)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(244,181,26,0.15)",
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm + 2,
  },
  headerTitle: {
    color: colors.white,
    fontSize: fontSize.title,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  headerBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
    gap: spacing.xs,
    borderWidth: 1,
    borderColor: "rgba(244,181,26,0.3)",
  },
  headerBadgeText: {
    color: colors.accent,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.extrabold,
    letterSpacing: 0.5,
  },
  mapOverlayTop: {
    position: "absolute",
    top: spacing.xxl,
    left: spacing.md,
    right: spacing.md,
    zIndex: 10,
    gap: spacing.xs,
  },
  compactStatsRow: {
    flexDirection: "column",
    gap: 4,
  },
  mapOverlayRight: {
    position: "absolute",
    top: spacing.xxl,
    right: spacing.md,
    zIndex: 10,
  },
  compactStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    paddingVertical: 3,
    paddingHorizontal: spacing.sm - 2,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(15,20,26,0.9)",
  },
  compactStatValue: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  compactStatLabel: {
    color: "rgba(255,255,255,0.5)",
    fontSize: 9,
    fontWeight: fontWeight.semibold,
  },
  filterRow: {
    flexDirection: "row",
    gap: spacing.xs,
    alignItems: "center",
    justifyContent: "flex-start",
  },
  styleSwitcher: {
    flexDirection: "row",
    gap: 3,
  },
  styleBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(15,20,26,0.9)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  styleBtnActive: {
    backgroundColor: colors.accent,
    borderColor: colors.accent,
  },
  stylePickerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 100,
    justifyContent: "flex-end",
  },
  stylePickerPanel: {
    backgroundColor: "#1e2a36",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 40,
    paddingTop: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
    borderBottomWidth: 0,
  },
  stylePickerHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: "rgba(255,255,255,0.15)",
    alignSelf: "center",
    marginBottom: 16,
  },
  stylePickerTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: colors.white,
    marginBottom: 12,
  },
  stylePickerItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 12,
    borderRadius: 12,
    marginBottom: 4,
  },
  stylePickerItemActive: {
    backgroundColor: "rgba(244,181,26,0.1)",
  },
  stylePickerItemText: {
    flex: 1,
    fontSize: 15,
    color: "rgba(255,255,255,0.6)",
    fontWeight: "500",
  },
  stylePickerItemTextActive: {
    color: colors.accent,
    fontWeight: "700",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingVertical: spacing.xs + 1,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
    backgroundColor: "rgba(15,20,26,0.9)",
  },
  filterBtnActive: {
    backgroundColor: "rgba(244,181,26,0.15)",
    borderColor: colors.accent,
  },
  filterBtnText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: "rgba(255,255,255,0.55)",
  },
  filterBtnTextActive: {
    color: colors.accent,
    fontWeight: fontWeight.bold,
  },
  mapContainer: {
    flex: 1,
    overflow: "hidden",
  },

  residentPanel: {
    flex: 1,
    backgroundColor: colors.surface,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.xl,
  },
  residentPanelTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  residentItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
    gap: spacing.md,
  },
  residentAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
  },
  residentName: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  residentAddress: {
    fontSize: fontSize.sm,
    color: colors.textTertiary,
    marginTop: 1,
  },
  residentStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
  },
  residentStatusText: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: spacing.xxl,
  },
  modalContent: {
    backgroundColor: "#1e2a36",
    borderRadius: borderRadius.xxl + 4,
    width: "100%",
    maxHeight: "80%",
    padding: spacing.xxl,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.06)",
  },
  modalHeader: {
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  modalAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: "rgba(255,255,255,0.06)",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: spacing.md,
    borderWidth: 3,
    borderColor: colors.accent,
  },
  modalAvatarImage: {
    width: 72,
    height: 72,
    borderRadius: 36,
  },
  modalName: {
    fontSize: fontSize.title,
    fontWeight: fontWeight.bold,
    color: colors.white,
  },
  modalBadge: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.5)",
    marginTop: spacing.xs,
    textAlign: "center",
  },
  modalInfoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  modalInfoText: {
    fontSize: fontSize.base,
    color: "rgba(255,255,255,0.7)",
    flex: 1,
  },
  modalDivider: {
    height: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    marginVertical: spacing.lg,
  },
  modalSectionTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.white,
    marginBottom: spacing.sm,
  },
  modalReportItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingVertical: spacing.sm,
  },
  modalReportType: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.white,
  },
  modalReportDate: {
    fontSize: fontSize.sm,
    color: "rgba(255,255,255,0.4)",
    marginTop: 1,
  },
  modalEmptyText: {
    fontSize: fontSize.md,
    color: "rgba(255,255,255,0.4)",
    fontStyle: "italic",
    marginVertical: spacing.sm,
  },
  modalProfileBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.accent,
    paddingVertical: spacing.md + 2,
    borderRadius: borderRadius.xl,
    marginTop: spacing.lg,
    gap: spacing.sm,
  },
  modalProfileBtnText: {
    color: "#0f141a",
    fontWeight: fontWeight.bold,
    fontSize: fontSize.lg,
  },
  modalCloseBtn: {
    position: "absolute",
    top: spacing.lg,
    right: spacing.lg,
    zIndex: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalActionsRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginTop: spacing.md,
  },
  modalActionBtnNav: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#17202b",
    paddingVertical: spacing.md,
    borderRadius: borderRadius.xl,
    gap: spacing.sm,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  modalActionBtnStreet: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#DBEAFE",
    paddingVertical: spacing.md,
    borderRadius: borderRadius.xl,
    gap: spacing.sm,
  },
  modalActionBtnTextWhite: {
    color: "#FFFFFF",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
  modalActionBtnTextBlue: {
    color: "#2563EB",
    fontSize: fontSize.base,
    fontWeight: fontWeight.bold,
  },
});
