import { StyleSheet } from "react-native";
import { colors, spacing, borderRadius, fontSize, fontWeight, shadow } from "../../constants/theme";

export const residentProfileStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F1F5F9",
  },
  header: {
    backgroundColor: colors.headerBg,
    borderBottomWidth: 0,
  },
  headerContent: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
  },
  backBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: "rgba(255,255,255,0.08)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.md,
  },
  headerTitle: {
    color: colors.white,
    fontSize: fontSize.xxl,
    fontWeight: fontWeight.bold,
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F1F5F9",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F1F5F9",
    padding: spacing.xxl,
  },
  errorText: {
    color: colors.textTertiary,
    fontSize: fontSize.lg,
  },

  // Hero
  heroSection: {
    backgroundColor: "#F1F5F9",
  },
  heroCover: {
    backgroundColor: colors.primaryDark,
    paddingTop: spacing.xxl + 20,
    paddingBottom: spacing.xxxl + 8,
    alignItems: "center",
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    position: "relative",
    overflow: "hidden",
  },
  heroCoverAccent: {
    position: "absolute",
    top: -50,
    right: -50,
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: "rgba(244,181,26,0.06)",
  },
  heroCoverAccent2: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(255,255,255,0.03)",
  },
  heroAvatarWrap: {
    marginBottom: spacing.md,
    alignItems: "center",
  },
  heroAvatar: {
    width: 88,
    height: 88,
    borderRadius: 44,
    backgroundColor: colors.borderLight,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 3,
    borderColor: colors.accent,
  },
  heroAvatarImage: {
    width: 82,
    height: 82,
    borderRadius: 41,
  },
  heroName: {
    fontSize: 22,
    fontWeight: fontWeight.extrabold,
    color: colors.white,
    letterSpacing: -0.3,
    textAlign: "center",
  },
  heroBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    backgroundColor: "rgba(244,181,26,0.12)",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 1,
    borderRadius: borderRadius.round,
    marginTop: spacing.sm,
  },
  heroBadgeText: {
    fontSize: fontSize.xs,
    color: colors.accent,
    fontWeight: fontWeight.semibold,
  },
  heroBody: {
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    gap: spacing.sm,
  },
  heroInfoCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  heroInfoIcon: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    justifyContent: "center",
    alignItems: "center",
  },
  heroInfoContent: {
    flex: 1,
  },
  heroInfoLabel: {
    fontSize: 9,
    color: colors.textTertiary,
    fontWeight: fontWeight.semibold,
    textTransform: "uppercase",
    letterSpacing: 0.6,
  },
  heroInfoValue: {
    fontSize: fontSize.base,
    color: colors.text,
    fontWeight: fontWeight.semibold,
    marginTop: 2,
  },
  heroLocation: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
    borderColor: colors.infoLight,
  },
  heroLocationText: {
    fontSize: fontSize.sm,
    color: colors.info,
    fontWeight: fontWeight.semibold,
    flex: 1,
  },
  heroActions: {
    flexDirection: "row",
    gap: spacing.sm,
    paddingTop: spacing.xs,
  },
  heroActionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.xs,
    paddingVertical: spacing.md - 2,
    borderRadius: borderRadius.lg,
    borderWidth: 1,
  },
  heroActionBtnText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
  },

  // Content
  contentSection: {
    padding: spacing.lg,
    paddingTop: spacing.sm + 2,
    gap: spacing.md,
  },
  sectionCard: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  sectionCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md + 2,
    paddingBottom: spacing.sm + 2,
  },
  sectionCardTitle: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.text,
  },
  sectionCardBadge: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    color: colors.textTertiary,
    backgroundColor: colors.borderLight,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.round,
    overflow: "hidden",
  },
  infoRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md - 2,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  infoRowText: {
    fontSize: fontSize.base,
    color: colors.textSecondary,
    flex: 1,
  },
  infoRowLink: {
    fontSize: fontSize.base,
    color: colors.info,
    fontWeight: fontWeight.semibold,
  },

  // Reports
  reportItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  reportIcon: {
    width: 36,
    height: 36,
    borderRadius: borderRadius.md,
    justifyContent: "center",
    alignItems: "center",
  },
  reportInfo: {
    flex: 1,
  },
  reportType: {
    fontSize: fontSize.base,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  reportMeta: {
    fontSize: fontSize.sm,
    color: colors.textTertiary,
    marginTop: 2,
  },
  reportStatusBadge: {
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.round,
  },
  reportStatusText: {
    fontSize: 9,
    fontWeight: fontWeight.bold,
  },
  emptyReportsText: {
    fontSize: fontSize.base,
    color: colors.textTertiary,
    fontStyle: "italic",
    textAlign: "center",
    paddingVertical: spacing.xxl,
  },

  // Map
  mapContainer: {
    height: 180,
    borderRadius: borderRadius.xl,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: colors.border,
  },

  // Modal
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: "flex-end",
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: borderRadius.xxl + 8,
    borderTopRightRadius: borderRadius.xxl + 8,
    maxHeight: "88%",
    paddingHorizontal: spacing.xxl,
    paddingTop: spacing.sm,
    paddingBottom: spacing.xxxl,
    ...shadow.modal,
  },
  modalHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    backgroundColor: colors.border,
    alignSelf: "center",
    marginBottom: spacing.md,
  },
  modalHeaderRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: spacing.sm,
  },
  modalBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.xs,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs + 2,
    borderRadius: borderRadius.round,
  },
  modalBadgeText: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
  },
  modalTitle: {
    fontSize: fontSize.title + 2,
    fontWeight: fontWeight.extrabold,
    color: colors.text,
    marginBottom: spacing.md,
    letterSpacing: -0.3,
  },
  modalResidentRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    marginBottom: spacing.md,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderLight,
  },
  modalResidentPhoto: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  modalResidentName: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    color: colors.text,
  },
  modalDate: {
    fontSize: fontSize.md,
    color: colors.textTertiary,
    marginTop: 1,
  },
  modalSectionLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    color: colors.textTertiary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  modalDescription: {
    fontSize: fontSize.base,
    color: colors.textSecondary,
    lineHeight: 22,
    marginBottom: spacing.md,
    backgroundColor: colors.background,
    padding: spacing.md + 2,
    borderRadius: borderRadius.lg,
  },
  modalMapContainer: {
    height: 160,
    borderRadius: borderRadius.lg,
    overflow: "hidden",
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalEvidenceRow: {
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  modalEvidenceImage: {
    width: 180,
    height: 140,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.borderLight,
  },
});
